"""Unit tests for `graphnet.utilities.magic.coordinates`.

Includes:
    1. A port of the 18 embedded self-tests from the canonical reference
       implementation (``~/mymars/mstarcam_trans.py``, a NumPy port of
       ``Mars/mstarcam/MStarCamTrans.cc``).
    2. Round-trip tests over randomized grids, including wrap boundaries.
    3. Scalar-vs-vectorized consistency checks.
    4. Exact-mode guards for `camera_prediction_to_radec`.
    5. A C++-parity fixture test (skipped if the fixture file has not yet
       been generated by the parallel MARS C++ job).
    6. A parity check against the canonical reference module directly
       (skipped if that module is not present on this machine).
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import numpy as np
import pytest

from graphnet.utilities.magic import coordinates as gc

# --- Shared fixtures ------------------------------------------------------

LATITUDE_DEG = 28.76  # La Palma, degrees; arbitrary but fixed for these tests.
COS_LAT = float(np.cos(np.deg2rad(LATITUDE_DEG)))
SIN_LAT = float(np.sin(np.deg2rad(LATITUDE_DEG)))
DIST_CAM = 28000.0  # mm; arbitrary test value, never used as a module default.

RTOL = 1e-10
ATOL = 1e-6

PARITY_FIXTURE_PATH = (
    Path(__file__).resolve().parents[1]
    / "data"
    / "magic"
    / "mstarcam_parity_fixtures.json"
)

_REFERENCE_MODULE_PATH = Path("~/mymars/mstarcam_trans.py").expanduser()


def _load_reference_module():
    """Load the canonical reference implementation as a standalone module."""
    spec = importlib.util.spec_from_file_location(
        "mstarcam_trans_reference", _REFERENCE_MODULE_PATH
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _ha_wrap_diff(a: float, b: float) -> float:
    diff = abs(a - b)
    return min(diff, 24.0 - diff)


def _az_wrap_diff(a: float, b: float) -> float:
    diff = abs(a - b)
    return min(diff, 360.0 - diff)


# --- 1. Ported self-tests from mstarcam_trans.py --------------------------
#
# Each `test_ref_N_*` mirrors the corresponding "[Test N]" block from the
# `if __name__ == "__main__":` section of ~/mymars/mstarcam_trans.py.


def test_ref_01_celestial_local_roundtrip() -> None:
    """[Test 1] Celestial <-> Local round-trip."""
    dec_test, ha_test = 22.0, 1.5
    theta, phi = gc.cel_to_loc(dec_test, ha_test, COS_LAT, SIN_LAT)
    dec_back, ha_back = gc.loc_to_cel(theta, phi, COS_LAT, SIN_LAT)
    assert dec_back == pytest.approx(dec_test, rel=RTOL, abs=ATOL)
    assert _ha_wrap_diff(ha_back, ha_test) == pytest.approx(0.0, abs=ATOL)


def test_ref_02_local_celestial_roundtrip() -> None:
    """[Test 2] Local <-> Celestial round-trip."""
    theta_test, phi_test = 30.0, 180.0
    dec, ha = gc.loc_to_cel(theta_test, phi_test, COS_LAT, SIN_LAT)
    theta_back, phi_back = gc.cel_to_loc(dec, ha, COS_LAT, SIN_LAT)
    assert theta_back == pytest.approx(theta_test, rel=RTOL, abs=ATOL)
    assert _az_wrap_diff(phi_back, phi_test) == pytest.approx(0.0, abs=0.1)


def test_ref_03_camera_center_maps_to_itself() -> None:
    """[Test 3] Camera center (0,0) should map to camera center coordinates."""
    dec0, ha0 = 22.0, 1.5
    X_center, Y_center = gc.cel0_cel_to_cam(
        dec0, ha0, dec0, ha0, DIST_CAM, COS_LAT, SIN_LAT
    )
    assert X_center == pytest.approx(0.0, abs=ATOL)
    assert Y_center == pytest.approx(0.0, abs=ATOL)


def test_ref_04_camera_celestial_roundtrip() -> None:
    """[Test 4] Camera <-> Celestial round-trip."""
    dec0, ha0 = 22.0, 1.5
    X_test, Y_test = 100.0, 50.0
    dec, ha = gc.cel0_cam_to_cel(
        dec0, ha0, X_test, Y_test, DIST_CAM, COS_LAT, SIN_LAT
    )
    X_back, Y_back = gc.cel0_cel_to_cam(
        dec0, ha0, dec, ha, DIST_CAM, COS_LAT, SIN_LAT
    )
    assert X_back == pytest.approx(X_test, rel=RTOL, abs=ATOL)
    assert Y_back == pytest.approx(Y_test, rel=RTOL, abs=ATOL)


def test_ref_05_celestial_camera_roundtrip() -> None:
    """[Test 5] Celestial <-> Camera round-trip."""
    dec0, ha0 = 22.0, 1.5
    dec_test, ha_test = 22.5, 1.6
    X, Y = gc.cel0_cel_to_cam(
        dec0, ha0, dec_test, ha_test, DIST_CAM, COS_LAT, SIN_LAT
    )
    dec_back, ha_back = gc.cel0_cam_to_cel(
        dec0, ha0, X, Y, DIST_CAM, COS_LAT, SIN_LAT
    )
    assert dec_back == pytest.approx(dec_test, rel=RTOL, abs=ATOL)
    assert _ha_wrap_diff(ha_back, ha_test) == pytest.approx(0.0, abs=ATOL)


def test_ref_06_local_camera_roundtrip() -> None:
    """[Test 6] Local <-> Camera round-trip."""
    theta0, phi0 = 30.0, 180.0
    theta_test, phi_test = 32.0, 182.0
    X, Y = gc.loc0_loc_to_cam(theta0, phi0, theta_test, phi_test, DIST_CAM)
    theta_back, phi_back = gc.loc0_cam_to_loc(theta0, phi0, X, Y, DIST_CAM)
    assert theta_back == pytest.approx(theta_test, rel=RTOL, abs=ATOL)
    assert _az_wrap_diff(phi_back, phi_test) == pytest.approx(0.0, abs=0.1)


def test_ref_07_vectorized_operations() -> None:
    """[Test 7] Vectorized operations (arrays)."""
    dec0, ha0 = 22.0, 1.5
    X_array = np.array([0.0, 100.0, -100.0, 50.0, -50.0])
    Y_array = np.array([0.0, 50.0, -50.0, 100.0, -100.0])
    dec_array, ha_array = gc.cel0_cam_to_cel(
        dec0, ha0, X_array, Y_array, DIST_CAM, COS_LAT, SIN_LAT
    )
    X_back, Y_back = gc.cel0_cel_to_cam(
        dec0, ha0, dec_array, ha_array, DIST_CAM, COS_LAT, SIN_LAT
    )
    assert np.allclose(X_back, X_array, rtol=RTOL, atol=ATOL)
    assert np.allclose(Y_back, Y_array, rtol=RTOL, atol=ATOL)


def test_ref_08_edge_case_zenith() -> None:
    """[Test 8] Edge case - zenith (theta close to 0)."""
    theta0, phi0 = 0.1, 180.0
    theta_test, phi_test = 2.0, 180.0
    X, Y = gc.loc0_loc_to_cam(theta0, phi0, theta_test, phi_test, DIST_CAM)
    theta_back, phi_back = gc.loc0_cam_to_loc(theta0, phi0, X, Y, DIST_CAM)
    assert theta_back == pytest.approx(theta_test, rel=RTOL, abs=ATOL)


def test_ref_09_edge_case_horizon() -> None:
    """[Test 9] Edge case - horizon (theta=90)."""
    theta0, phi0 = 89.0, 180.0
    theta_test, phi_test = 91.0, 180.0
    X, Y = gc.loc0_loc_to_cam(theta0, phi0, theta_test, phi_test, DIST_CAM)
    theta_back, phi_back = gc.loc0_cam_to_loc(theta0, phi0, X, Y, DIST_CAM)
    assert theta_back == pytest.approx(theta_test, rel=RTOL, abs=ATOL)


def test_ref_10_multiple_angles_around_the_sky() -> None:
    """[Test 10] Multiple angles around the sky."""
    dec0, ha0 = 22.0, 1.5
    test_dec = np.array([20.0, 22.0, 24.0, 22.0, 22.0])
    test_ha = np.array([1.4, 1.5, 1.6, 1.3, 1.7])
    X, Y = gc.cel0_cel_to_cam(
        dec0, ha0, test_dec, test_ha, DIST_CAM, COS_LAT, SIN_LAT
    )
    dec_back, ha_back = gc.cel0_cam_to_cel(
        dec0, ha0, X, Y, DIST_CAM, COS_LAT, SIN_LAT
    )
    ha_diff = np.minimum(
        np.abs(ha_back - test_ha), 24.0 - np.abs(ha_back - test_ha)
    )
    assert np.allclose(dec_back, test_dec, rtol=RTOL, atol=ATOL)
    assert np.allclose(ha_diff, 0.0, atol=ATOL)


def test_ref_11_starcamtrans_class() -> None:
    """[Test 11] StarCamTrans class."""
    trans = gc.StarCamTrans(DIST_CAM, COS_LAT, SIN_LAT)
    dec0, ha0 = 22.0, 1.5
    X_test, Y_test = 100.0, 50.0
    dec, ha = trans.cel0_cam_to_cel(dec0, ha0, X_test, Y_test)
    X_back, Y_back = trans.cel0_cel_to_cam(dec0, ha0, dec, ha)
    assert X_back == pytest.approx(X_test, rel=RTOL, abs=ATOL)
    assert Y_back == pytest.approx(Y_test, rel=RTOL, abs=ATOL)


def test_ref_12_hour_angle_wrap_around() -> None:
    """[Test 12] Hour angle wrap-around."""
    dec0, ha0 = 22.0, 23.5
    dec_test, ha_test = 22.5, 0.5
    X, Y = gc.cel0_cel_to_cam(
        dec0, ha0, dec_test, ha_test, DIST_CAM, COS_LAT, SIN_LAT
    )
    dec_back, ha_back = gc.cel0_cam_to_cel(
        dec0, ha0, X, Y, DIST_CAM, COS_LAT, SIN_LAT
    )
    assert dec_back == pytest.approx(dec_test, rel=RTOL, abs=ATOL)
    assert _ha_wrap_diff(ha_back, ha_test) == pytest.approx(0.0, abs=ATOL)


def test_ref_13_azimuth_wrap_around() -> None:
    """[Test 13] Azimuth wrap-around."""
    theta0, phi0 = 30.0, 359.0
    theta_test, phi_test = 32.0, 1.0
    X, Y = gc.loc0_loc_to_cam(theta0, phi0, theta_test, phi_test, DIST_CAM)
    theta_back, phi_back = gc.loc0_cam_to_loc(theta0, phi0, X, Y, DIST_CAM)
    assert theta_back == pytest.approx(theta_test, rel=RTOL, abs=ATOL)
    assert _az_wrap_diff(phi_back, phi_test) == pytest.approx(0.0, abs=1.0)


def test_ref_14_scalar_vs_array_consistency() -> None:
    """[Test 14] Scalar vs array consistency."""
    dec0, ha0 = 22.0, 1.5
    X_scalar, Y_scalar = 100.0, 50.0
    dec_scalar, ha_scalar = gc.cel0_cam_to_cel(
        dec0, ha0, X_scalar, Y_scalar, DIST_CAM, COS_LAT, SIN_LAT
    )
    dec_array, ha_array = gc.cel0_cam_to_cel(
        dec0,
        ha0,
        np.array([X_scalar]),
        np.array([Y_scalar]),
        DIST_CAM,
        COS_LAT,
        SIN_LAT,
    )
    assert dec_scalar == pytest.approx(dec_array[0], rel=RTOL, abs=ATOL)
    assert ha_scalar == pytest.approx(ha_array[0], rel=RTOL, abs=ATOL)


def test_ref_15_large_camera_distances() -> None:
    """[Test 15] Large camera-plane displacements."""
    dec0, ha0 = 22.0, 1.5
    X_test, Y_test = 500.0, 300.0
    dec, ha = gc.cel0_cam_to_cel(
        dec0, ha0, X_test, Y_test, DIST_CAM, COS_LAT, SIN_LAT
    )
    X_back, Y_back = gc.cel0_cel_to_cam(
        dec0, ha0, dec, ha, DIST_CAM, COS_LAT, SIN_LAT
    )
    assert X_back == pytest.approx(X_test, rel=RTOL, abs=ATOL)
    assert Y_back == pytest.approx(Y_test, rel=RTOL, abs=ATOL)


def test_ref_16_negative_camera_coordinates() -> None:
    """[Test 16] Negative camera coordinates."""
    dec0, ha0 = 22.0, 1.5
    X_test, Y_test = -100.0, -50.0
    dec, ha = gc.cel0_cam_to_cel(
        dec0, ha0, X_test, Y_test, DIST_CAM, COS_LAT, SIN_LAT
    )
    X_back, Y_back = gc.cel0_cel_to_cam(
        dec0, ha0, dec, ha, DIST_CAM, COS_LAT, SIN_LAT
    )
    assert X_back == pytest.approx(X_test, rel=RTOL, abs=ATOL)
    assert Y_back == pytest.approx(Y_test, rel=RTOL, abs=ATOL)


def test_ref_17_various_declinations() -> None:
    """[Test 17] Various declinations."""
    ha0 = 1.5
    test_decs = np.array([-30.0, 0.0, 30.0, 60.0, 85.0])
    for dec0 in test_decs:
        dec_test = dec0 + 0.5
        ha_test = ha0 + 0.1
        X, Y = gc.cel0_cel_to_cam(
            dec0, ha0, dec_test, ha_test, DIST_CAM, COS_LAT, SIN_LAT
        )
        dec_back, ha_back = gc.cel0_cam_to_cel(
            dec0, ha0, X, Y, DIST_CAM, COS_LAT, SIN_LAT
        )
        assert dec_back == pytest.approx(dec_test, rel=RTOL, abs=ATOL)
        assert _ha_wrap_diff(ha_back, ha_test) == pytest.approx(0.0, abs=ATOL)


def test_ref_18_hour_angle_range() -> None:
    """[Test 18] Hour angle range (0-24)."""
    dec0 = 22.0
    X_test, Y_test = 100.0, 50.0
    for ha0 in [0.0, 6.0, 12.0, 18.0, 23.9]:
        dec, ha = gc.cel0_cam_to_cel(
            dec0, ha0, X_test, Y_test, DIST_CAM, COS_LAT, SIN_LAT
        )
        assert 0.0 <= ha < 24.0
        X_back, Y_back = gc.cel0_cel_to_cam(
            dec0, ha0, dec, ha, DIST_CAM, COS_LAT, SIN_LAT
        )
        assert X_back == pytest.approx(X_test, rel=RTOL, abs=ATOL)
        assert Y_back == pytest.approx(Y_test, rel=RTOL, abs=ATOL)


# --- 2. Round-trip tests over randomized grids, including wrap boundaries -


@pytest.mark.parametrize("seed", [0, 1, 2])
def test_loc0_roundtrip_random_grid(seed: int) -> None:
    """`loc0_loc_to_cam` <-> `loc0_cam_to_loc` over a random grid."""
    rng = np.random.default_rng(seed)
    n = 200
    theta0 = rng.uniform(1.0, 89.0, size=n)
    phi0 = rng.uniform(0.0, 360.0, size=n)
    dtheta = rng.uniform(-5.0, 5.0, size=n)
    dphi = rng.uniform(-5.0, 5.0, size=n)
    theta = np.clip(theta0 + dtheta, 0.5, 89.5)
    phi = phi0 + dphi

    X, Y = gc.loc0_loc_to_cam(theta0, phi0, theta, phi, DIST_CAM)
    theta_back, phi_back = gc.loc0_cam_to_loc(theta0, phi0, X, Y, DIST_CAM)

    assert np.allclose(theta_back, theta, rtol=RTOL, atol=ATOL)
    phi_diff = np.minimum(
        np.abs(phi_back - phi) % 360.0, 360.0 - np.abs(phi_back - phi) % 360.0
    )
    assert np.allclose(phi_diff, 0.0, atol=1e-3)


@pytest.mark.parametrize("seed", [0, 1, 2])
def test_cel0_roundtrip_random_grid(seed: int) -> None:
    """`cel0_cel_to_cam` <-> `cel0_cam_to_cel` over a random grid."""
    rng = np.random.default_rng(seed + 100)
    n = 200
    dec0 = rng.uniform(-40.0, 80.0, size=n)
    ha0 = rng.uniform(0.0, 24.0, size=n)
    dec = np.clip(dec0 + rng.uniform(-2.0, 2.0, size=n), -89.0, 89.0)
    ha = ha0 + rng.uniform(-0.2, 0.2, size=n)

    X, Y = gc.cel0_cel_to_cam(dec0, ha0, dec, ha, DIST_CAM, COS_LAT, SIN_LAT)
    dec_back, ha_back = gc.cel0_cam_to_cel(
        dec0, ha0, X, Y, DIST_CAM, COS_LAT, SIN_LAT
    )

    assert np.allclose(dec_back, dec, rtol=RTOL, atol=ATOL)
    ha_diff = np.minimum(
        np.abs(ha_back - ha % 24.0), 24.0 - np.abs(ha_back - ha % 24.0)
    )
    assert np.allclose(ha_diff, 0.0, atol=ATOL)


@pytest.mark.parametrize("seed", [0, 1, 2])
def test_cel_loc_roundtrip_random_grid_with_wrap(seed: int) -> None:
    """`cel_to_loc` <-> `loc_to_cel` over a grid spanning HA wrap boundaries."""
    rng = np.random.default_rng(seed + 200)
    n = 200
    dec = rng.uniform(-85.0, 85.0, size=n)
    # Include values that straddle the [0, 24) wrap boundary explicitly.
    ha = np.concatenate(
        [
            rng.uniform(0.0, 24.0, size=n - 4),
            np.array([-0.001, 0.0, 23.999, 24.0]),
        ]
    )
    dec = np.concatenate([dec[: n - 4], np.array([22.0, 22.0, 22.0, 22.0])])

    theta, phi = gc.cel_to_loc(dec, ha, COS_LAT, SIN_LAT)
    dec_back, ha_back = gc.loc_to_cel(theta, phi, COS_LAT, SIN_LAT)

    assert np.allclose(dec_back, dec, rtol=RTOL, atol=ATOL)
    ha_wrapped = gc.wrap24(ha)
    ha_diff = np.minimum(
        np.abs(ha_back - ha_wrapped), 24.0 - np.abs(ha_back - ha_wrapped)
    )
    assert np.allclose(ha_diff, 0.0, atol=ATOL)


def test_wrap24_boundaries() -> None:
    """`wrap24` handles exact boundaries and negative/large inputs."""
    assert gc.wrap24(0.0) == pytest.approx(0.0)
    assert gc.wrap24(24.0) == pytest.approx(0.0)
    assert gc.wrap24(-0.5) == pytest.approx(23.5)
    assert gc.wrap24(25.5) == pytest.approx(1.5)
    assert np.allclose(
        gc.wrap24(np.array([-24.0, 0.0, 24.0, 48.0])), [0.0, 0.0, 0.0, 0.0]
    )


def test_wrap360_boundaries() -> None:
    """`wrap360` handles exact boundaries and negative/large inputs."""
    assert gc.wrap360(0.0) == pytest.approx(0.0)
    assert gc.wrap360(360.0) == pytest.approx(0.0)
    assert gc.wrap360(-1.0) == pytest.approx(359.0)
    assert gc.wrap360(361.0) == pytest.approx(1.0)


# --- 3. Scalar-vs-vectorized consistency -----------------------------------


def test_scalar_vs_vector_all_public_transforms() -> None:
    """All main transforms give identical scalar and length-1-array results."""
    dec0, ha0 = 22.0, 1.5
    theta0, phi0 = 30.0, 180.0
    X, Y = 123.4, -56.7
    dec, ha = 24.1, 2.0
    theta, phi = 32.0, 182.0

    # cel_to_loc / loc_to_cel
    t_s, p_s = gc.cel_to_loc(dec, ha, COS_LAT, SIN_LAT)
    t_v, p_v = gc.cel_to_loc(np.array([dec]), np.array([ha]), COS_LAT, SIN_LAT)
    assert np.isscalar(t_s) or isinstance(t_s, float)
    assert t_s == pytest.approx(t_v[0])
    assert p_s == pytest.approx(p_v[0])

    d_s, h_s = gc.loc_to_cel(theta, phi, COS_LAT, SIN_LAT)
    d_v, h_v = gc.loc_to_cel(
        np.array([theta]), np.array([phi]), COS_LAT, SIN_LAT
    )
    assert d_s == pytest.approx(d_v[0])
    assert h_s == pytest.approx(h_v[0])

    # loc0_loc_to_cam / loc0_cam_to_loc
    X_s, Y_s = gc.loc0_loc_to_cam(theta0, phi0, theta, phi, DIST_CAM)
    X_v, Y_v = gc.loc0_loc_to_cam(
        np.array([theta0]),
        np.array([phi0]),
        np.array([theta]),
        np.array([phi]),
        DIST_CAM,
    )
    assert X_s == pytest.approx(X_v[0])
    assert Y_s == pytest.approx(Y_v[0])

    t2_s, p2_s = gc.loc0_cam_to_loc(theta0, phi0, X, Y, DIST_CAM)
    t2_v, p2_v = gc.loc0_cam_to_loc(
        np.array([theta0]),
        np.array([phi0]),
        np.array([X]),
        np.array([Y]),
        DIST_CAM,
    )
    assert t2_s == pytest.approx(t2_v[0])
    assert p2_s == pytest.approx(p2_v[0])

    # cel0_cam_to_cel / cel0_cel_to_cam
    dec_s, ha_s = gc.cel0_cam_to_cel(
        dec0, ha0, X, Y, DIST_CAM, COS_LAT, SIN_LAT
    )
    dec_v, ha_v = gc.cel0_cam_to_cel(
        dec0, ha0, np.array([X]), np.array([Y]), DIST_CAM, COS_LAT, SIN_LAT
    )
    assert dec_s == pytest.approx(dec_v[0])
    assert ha_s == pytest.approx(ha_v[0])

    X3_s, Y3_s = gc.cel0_cel_to_cam(
        dec0, ha0, dec, ha, DIST_CAM, COS_LAT, SIN_LAT
    )
    X3_v, Y3_v = gc.cel0_cel_to_cam(
        dec0, ha0, np.array([dec]), np.array([ha]), DIST_CAM, COS_LAT, SIN_LAT
    )
    assert X3_s == pytest.approx(X3_v[0])
    assert Y3_s == pytest.approx(Y3_v[0])


def test_scalar_vs_vector_angular_separation() -> None:
    """`angular_separation_deg` gives identical scalar and vector results."""
    sep_s = gc.angular_separation_deg(10.0, 20.0, 11.0, 21.0)
    sep_v = gc.angular_separation_deg(
        np.array([10.0]), np.array([20.0]), np.array([11.0]), np.array([21.0])
    )
    assert sep_s == pytest.approx(sep_v[0])


# --- Angular separation correctness ----------------------------------------


def test_angular_separation_deg_known_values() -> None:
    """Sanity-check `angular_separation_deg` against known geometric cases."""
    # Same point -> zero separation.
    assert gc.angular_separation_deg(10.0, 20.0, 10.0, 20.0) == pytest.approx(
        0.0, abs=1e-9
    )

    # Separation along a declination-only offset (great-circle == delta dec).
    sep = gc.angular_separation_deg(10.0, 0.0, 10.0, 1.0)
    assert sep == pytest.approx(1.0, abs=1e-9)

    # Antipodal points on the sphere (ra offset 180 deg, dec negated) -> 180 deg.
    sep = gc.angular_separation_deg(0.0, 30.0, 180.0, -30.0)
    assert sep == pytest.approx(180.0, abs=1e-6)

    # RA in hours must match RA in degrees scaled by 15.
    sep_deg = gc.angular_separation_deg(30.0, 10.0, 45.0, 12.0, ra_unit="deg")
    sep_hours = gc.angular_separation_deg(
        2.0, 10.0, 3.0, 12.0, ra_unit="hours"
    )
    assert sep_deg == pytest.approx(sep_hours, abs=1e-9)


def test_angular_separation_deg_invalid_unit_raises() -> None:
    """An unsupported `ra_unit` raises `ValueError`."""
    with pytest.raises(ValueError):
        gc.angular_separation_deg(0.0, 0.0, 1.0, 1.0, ra_unit="radians")


# --- 4. Exact-mode guard for camera_prediction_to_radec ---------------------


def test_camera_prediction_to_radec_exact_requires_corrected_pointing() -> (
    None
):
    """Exact mode raises if corrected pointing / LST are not all supplied."""
    with pytest.raises(ValueError):
        gc.camera_prediction_to_radec(
            10.0,
            20.0,
            camera_dist_mm=DIST_CAM,
            cos_lat=COS_LAT,
            sin_lat=SIN_LAT,
        )
    # Partial arguments still raise.
    with pytest.raises(ValueError):
        gc.camera_prediction_to_radec(
            10.0,
            20.0,
            camera_dist_mm=DIST_CAM,
            cos_lat=COS_LAT,
            sin_lat=SIN_LAT,
            corr_dec_deg=22.0,
            corr_ha_hours=1.5,
            # lst_hours missing
        )


def test_camera_prediction_to_radec_exact_mode_matches_manual_chain() -> None:
    """Exact mode output matches manually chaining `cel0_cam_to_cel` + RA/HA."""
    dec0, ha0 = 22.0, 1.5
    X, Y = 100.0, 50.0
    lst = 5.0

    ra_hours, dec_deg = gc.camera_prediction_to_radec(
        X,
        Y,
        camera_dist_mm=DIST_CAM,
        cos_lat=COS_LAT,
        sin_lat=SIN_LAT,
        lst_hours=lst,
        corr_dec_deg=dec0,
        corr_ha_hours=ha0,
    )
    dec_expected, ha_expected = gc.cel0_cam_to_cel(
        dec0, ha0, X, Y, DIST_CAM, COS_LAT, SIN_LAT
    )
    ra_expected = gc.ra_hours_from_lst_and_ha(lst, ha_expected)

    assert dec_deg == pytest.approx(dec_expected, rel=RTOL, abs=ATOL)
    assert ra_hours == pytest.approx(ra_expected, rel=RTOL, abs=ATOL)


def test_camera_prediction_to_radec_approx_mode_requires_explicit_opt_in() -> (
    None
):
    """`approx_nominal` requires nominal pointing + LST; default mode never uses it."""
    with pytest.raises(ValueError):
        gc.camera_prediction_to_radec(
            10.0,
            20.0,
            camera_dist_mm=DIST_CAM,
            cos_lat=COS_LAT,
            sin_lat=SIN_LAT,
            mode="approx_nominal",
            # nominal_dec_deg / nominal_ha_hours / lst_hours missing
        )

    # With all approx-mode arguments supplied, it succeeds and does not
    # require corrected-pointing arguments.
    ra_hours, dec_deg = gc.camera_prediction_to_radec(
        100.0,
        50.0,
        camera_dist_mm=DIST_CAM,
        cos_lat=COS_LAT,
        sin_lat=SIN_LAT,
        mode="approx_nominal",
        nominal_dec_deg=22.0,
        nominal_ha_hours=1.5,
        lst_hours=5.0,
    )
    assert np.isfinite(ra_hours)
    assert np.isfinite(dec_deg)


def test_camera_prediction_to_radec_invalid_mode_raises() -> None:
    """An unsupported `mode` raises `ValueError`."""
    with pytest.raises(ValueError):
        gc.camera_prediction_to_radec(
            10.0,
            20.0,
            camera_dist_mm=DIST_CAM,
            cos_lat=COS_LAT,
            sin_lat=SIN_LAT,
            mode="bogus",
            corr_dec_deg=22.0,
            corr_ha_hours=1.5,
            lst_hours=5.0,
        )


# --- 5. C++-parity fixture test ---------------------------------------------


def test_cpp_parity_fixtures() -> None:
    """Compare against fixtures generated by a MARS C++ (MStarCamTrans) job.

    Skipped if the fixture file has not yet been produced -- it is generated
    by a parallel MARS C++ job and must not be fabricated here. Expected
    fixture schema: a JSON list of records, each with at minimum
    ``dec0_deg``, ``ha0_hours``, ``dec_deg``, ``ha_hours``, ``dist_cam_mm``,
    ``cos_lat``, ``sin_lat``, ``x_mm``, ``y_mm``.
    """
    if not PARITY_FIXTURE_PATH.exists():
        pytest.skip(
            f"C++ parity fixture not found at {PARITY_FIXTURE_PATH}; it is "
            "generated by a MARS C++ job running in parallel and must not "
            "be fabricated here."
        )

    with open(PARITY_FIXTURE_PATH) as handle:
        fixtures = json.load(handle)

    assert fixtures, "Parity fixture file is empty."

    for record in fixtures:
        X, Y = gc.cel0_cel_to_cam(
            record["dec0_deg"],
            record["ha0_hours"],
            record["dec_deg"],
            record["ha_hours"],
            record["dist_cam_mm"],
            record["cos_lat"],
            record["sin_lat"],
        )
        assert X == pytest.approx(record["x_mm"], abs=gc.PARITY_ATOL_MM)
        assert Y == pytest.approx(record["y_mm"], abs=gc.PARITY_ATOL_MM)

        if "theta0_deg" in record and "phi0_deg" in record:
            theta0, phi0 = gc.cel_to_loc(
                record["dec0_deg"],
                record["ha0_hours"],
                record["cos_lat"],
                record["sin_lat"],
            )
            assert theta0 == pytest.approx(
                record["theta0_deg"], abs=gc.PARITY_ATOL_DEG
            )
            assert phi0 == pytest.approx(
                record["phi0_deg"], abs=gc.PARITY_ATOL_DEG
            )


# --- 6. Parity check against the canonical reference module directly -------


@pytest.mark.skipif(
    not _REFERENCE_MODULE_PATH.exists(),
    reason=f"Reference implementation not found at {_REFERENCE_MODULE_PATH}",
)
def test_parity_with_reference_mstarcam_trans() -> None:
    """Outputs match `~/mymars/mstarcam_trans.py` on a random grid, to 1e-12."""
    ref = _load_reference_module()

    rng = np.random.default_rng(42)
    n = 500
    dec0 = rng.uniform(-40.0, 80.0, size=n)
    ha0 = rng.uniform(0.0, 24.0, size=n)
    dec = np.clip(dec0 + rng.uniform(-2.0, 2.0, size=n), -89.0, 89.0)
    ha = gc.wrap24(ha0 + rng.uniform(-0.2, 0.2, size=n))

    # cel_to_loc / loc_to_cel parity
    theta_ref, phi_ref = ref.cel_to_loc(dec, ha, COS_LAT, SIN_LAT)
    theta_new, phi_new = gc.cel_to_loc(dec, ha, COS_LAT, SIN_LAT)
    assert np.allclose(theta_new, theta_ref, atol=1e-12, rtol=1e-12)
    assert np.allclose(phi_new, phi_ref, atol=1e-12, rtol=1e-12)

    dec_ref, ha_ref = ref.loc_to_cel(theta_ref, phi_ref, COS_LAT, SIN_LAT)
    dec_new, ha_new = gc.loc_to_cel(theta_new, phi_new, COS_LAT, SIN_LAT)
    assert np.allclose(dec_new, dec_ref, atol=1e-12, rtol=1e-12)
    assert np.allclose(ha_new, ha_ref, atol=1e-12, rtol=1e-12)

    # cel0_cel_to_cam / cel0_cam_to_cel parity
    X_ref, Y_ref = ref.cel0_cel_to_cam(
        dec0, ha0, dec, ha, DIST_CAM, COS_LAT, SIN_LAT
    )
    X_new, Y_new = gc.cel0_cel_to_cam(
        dec0, ha0, dec, ha, DIST_CAM, COS_LAT, SIN_LAT
    )
    assert np.allclose(X_new, X_ref, atol=1e-12, rtol=1e-12)
    assert np.allclose(Y_new, Y_ref, atol=1e-12, rtol=1e-12)

    dec2_ref, ha2_ref = ref.cel0_cam_to_cel(
        dec0, ha0, X_ref, Y_ref, DIST_CAM, COS_LAT, SIN_LAT
    )
    dec2_new, ha2_new = gc.cel0_cam_to_cel(
        dec0, ha0, X_new, Y_new, DIST_CAM, COS_LAT, SIN_LAT
    )
    assert np.allclose(dec2_new, dec2_ref, atol=1e-12, rtol=1e-12)
    assert np.allclose(ha2_new, ha2_ref, atol=1e-12, rtol=1e-12)

    # loc0_loc_to_cam / loc0_cam_to_loc parity (independent local-only grid)
    theta0 = rng.uniform(1.0, 89.0, size=n)
    phi0 = rng.uniform(0.0, 360.0, size=n)
    theta = np.clip(theta0 + rng.uniform(-5.0, 5.0, size=n), 0.5, 89.5)
    phi = phi0 + rng.uniform(-5.0, 5.0, size=n)

    X3_ref, Y3_ref = ref.loc0_loc_to_cam(theta0, phi0, theta, phi, DIST_CAM)
    X3_new, Y3_new = gc.loc0_loc_to_cam(theta0, phi0, theta, phi, DIST_CAM)
    assert np.allclose(X3_new, X3_ref, atol=1e-12, rtol=1e-12)
    assert np.allclose(Y3_new, Y3_ref, atol=1e-12, rtol=1e-12)

    theta_b_ref, phi_b_ref = ref.loc0_cam_to_loc(
        theta0, phi0, X3_ref, Y3_ref, DIST_CAM
    )
    theta_b_new, phi_b_new = gc.loc0_cam_to_loc(
        theta0, phi0, X3_new, Y3_new, DIST_CAM
    )
    assert np.allclose(theta_b_new, theta_b_ref, atol=1e-12, rtol=1e-12)
    assert np.allclose(phi_b_new, phi_b_ref, atol=1e-12, rtol=1e-12)
