path: /mnt/scratch/jarred/LMDB_2M_gammas/za05to35.lmdb
graph_definition:
  arguments:
    columns: [0, 1, 2]
    detector:
      arguments: {}
      class_name: MAGICDetectorFixed
    dtype: torch.float32
    nb_nearest_neighbours: 8
    node_definition:
      arguments: {}
      class_name: NodesAsPulses
    input_feature_names: ['x_cam', 'y_cam', 'tel_id', 't', 'signal', 'telescope_phi', 'telescope_theta']
  class_name: KNNGraph
pulsemaps:
  - total
features:
  - x_cam
  - y_cam
  - tel_id
  - t
  - signal
  - telescope_phi
  - telescope_theta
truth:
  - particle_id
  - true_energy
  - true_theta
  - true_phi
  - telescope_phi
  - telescope_theta
index_column: event_id
truth_table: truth
seed: 21
labels:
  direction:
    arguments:
      azimuth_key: "true_phi"
      zenith_key: "true_theta"
    class_name: Direction
  true_telescope:
    arguments:
      telescope_phi_key: "telescope_phi"
      telescope_theta_key: "telescope_theta"
    class_name: TrueTelescopeLabel
  direction_and_axis:
    arguments:
      dir_key: "direction"
      tel_key: "true_telescope"
      key: "direction_and_axis"
    class_name: DirectionWithAxisLabel
selection:
  test: "event_id % 10 == 0 and particle_id == 1"
  validation: "event_id % 10 == 1 and particle_id == 1"
  train: "event_id % 10 > 1 and particle_id == 1"
# selection:  # ~1/6th dataset size
#   test: "event_id % 6 == 0 and (event_id // 6) % 10 == 0"      # ~2,000 events
#   validation: "event_id % 6 == 0 and (event_id // 6) % 10 == 1"  # ~2,000 events
#   train: "event_id % 6 == 0 and (event_id // 6) % 10 > 1"     # ~16,000 events
