arguments:
  graph_definition:
    ModelConfig:
      class_name: KNNGraph
      arguments:
        detector:
          ModelConfig:
            class_name: MAGICDetectorFixed
            arguments: {}
        node_definition:
          ModelConfig:
            class_name: NodesAsPulses
            arguments: {}
        nb_nearest_neighbours: 8
  backbone:
    ModelConfig:
      class_name: MagicDeepSky
      arguments:
        hidden_dim: 128
        seq_length: 128
        depth: 4
        head_size: 32
        n_rel: 3
        scaled_emb: true
        n_features: 7
        include_dynedge: false
  tasks:
    - ModelConfig:
        class_name: AngularOffsetReconstructionWithKappa
        arguments:
          hidden_size: 128
          target_labels: angular_offset
          loss_function:
            ModelConfig:
              class_name: MAGICFieldOfViewLoss
              arguments:
                fov_radius_deg: 2.50
                fov_penalty_weight: 2000.0
  optimizer_class: '!class torch.optim.adamw AdamW'
  optimizer_kwargs:
    lr: 0.0005
    weight_decay: 0.05
  scheduler_class: '!class torch.optim.lr_scheduler CosineAnnealingLR'
  scheduler_kwargs:
    T_max: 10
    eta_min: 1e-5
class_name: StandardModel

