arguments:
  graph_definition:
    ModelConfig:
      class_name: KNNGraph
      arguments:
        detector:
          ModelConfig:
            class_name: MAGICDetectorFixed
            arguments: {}
        node_definition:
          ModelConfig:
            class_name: MAGICLimitedNodes
            arguments:
              max_pulses: 512
              sampling_strategy: "signal"
        nb_nearest_neighbours: 8
  backbone:
    ModelConfig:
      class_name: MagicDeepSky
      arguments:
        hidden_dim: 128
        mlp_dim: 256
        seq_length: 128
        depth: 4
        head_size: 32
        n_rel: 3
        scaled_emb: true
        n_features: 7
        include_dynedge: false
  tasks:
    - ModelConfig:
        class_name: DirectionReconstructionWithKappa
        arguments:
          hidden_size: 128
          target_labels: direction_and_axis
          loss_function:
            ModelConfig:
              class_name: MAGICEnsembleLoss
              arguments:
                vmf_weight: 1.0
                fov_weight: 50.0
                fov_radius_deg: 2.50
                fov_loss_mode: logcosh
  optimizer_class: '!class torch.optim.adamw AdamW'
  optimizer_kwargs:
    lr: 0.0005
    weight_decay: 0.05
  scheduler_class: '!class torch.optim.lr_scheduler CosineAnnealingLR'
  scheduler_kwargs:
    T_max: 30
    eta_min: 1e-5
class_name: StandardModel

